### ISSUE TITLE
RTEConfig file throwing java.util.regex.PatternSyntaxException

### ISSUE THREAD

**Issue by avi-77** [ARM-software/cmsis-pack-eclipse#100]
Hi @edriouk,
 
The recent update to the **WildCards.java** class in the **com.arm.cmsis.pack.common** plugin (version 2.7.0) is throwing a PatternSyntaxException, if the RTEConfig file has the "**Use all latest Packs**" checkbox unchecked. 

Could you please look into this issue?

![rteconfig_uselatestpack_checkbox_unchecked](https://user-images.githubusercontent.com/79654418/178612517-983fc00d-aa2c-410a-ac4f-dcaf2480d75d.PNG)

![rteconfig_uselatestpack_checkbox_unchecked1](https://user-images.githubusercontent.com/79654418/178612562-06210136-a601-4a99-a472-b91854b0d868.PNG)

**Comment by edriouk** [comment]
Fixed in 2.8.0
