### ISSUE TITLE
The 'Releases' link should be in readme.md at some top position

### ISSUE THREAD

**Issue by powerbroker** [ARM-software/cmsis-pack-eclipse#111]
The binary releases are available to download at 'https://github.com/ARM-software/cmsis-pack-eclipse/releases', but there is absolutely no direct link to.

Search engines(e.g. goooooooooooogol) send users onto https://github.com/ARM-software/cmsis-pack-eclipse, where 'readme.md' is shown. Reading the readme with no success in obtaining direct link to files (the 'Download the CMSISPackPlugin_x.x.zip from corresponding release' term could be that link) user have to guess, that desired binaries are under '.../releases' sublink, or examine 'Tags' or so.

Direct link to releases is much-much more valuable for visitors of https://github.com/ARM-software/cmsis-pack-eclipse than all that copyractic intellectoilet property bloat, so it must be near the top of readme.md

**Comment by edriouk** [comment]
Implemented in 2.10.0
