### ISSUE TITLE
Blank STM32F0xx project must be out-of-the-box compilable

### ISSUE THREAD

**Issue by powerbroker** [ARM-software/cmsis-pack-eclipse#112]
Set up ARM Cross GCC toolchain in Preferences/MCU/Global Arm Toolchain, e.g. arm-none-eabi-gcc 13.2.Rel1
Configure Eclipse CMSIS extension to support STM32F0xx by installing "Device Specific" Keil.STM32F0xx_DFP

Create new "C managed build" C project "STM32F0xx C/C++ Project". Leave "Use newlib nano" option enabled (by default).
Build it.

Enjoy build failure with '../kernel/src/newlib/cxx.cpp:51:5: error: 'abort' was not declared in this scope; did you mean 'std::abort'?' message.

The default project skeleton(containing 'main' method, pre-configured startup, debugging support, etc.) must be compilable and runnable, so user don't have to fix framework errors each time new project is created.

**Comment by edriouk** [comment]
@powerbroker, the problem you are describing, refers to another plugings that are not related to this repository.
Please address you issues here: https://github.com/gnuarmeclipse
