### ISSUE TITLE
Renaming (STM32F0xx) framework *.c file to exclude it out of build scope(e.g. to *.c.bak) must never crash build procedure

### ISSUE THREAD

**Issue by powerbroker** [ARM-software/cmsis-pack-eclipse#113]
Configure Eclipse CMSIS extension to support e.g. STM32F0xx by installing "Device Specific" pack, e.g. Keil.STM32F0xx_DFP

Create new "C managed build" C project with CMSIS framework, e.g. "STM32F0xx C/C++ Project".
Rename /src/stm32f0xx_hal_msp.c ->stm32f0xx_hal_msp.c.bak, so compiler have no more interest in it(this is useful step to turn generated project skeleton into LowLayer-drivers-based out of HAL-drivers-based default one by excluding unnecessary HAL-related source files without removing them)

Build the project.

Enjoy build procedure crash: src/subdir.mk:30: *** missing separator.  Stop.

Open the crash source - 'subdir.mk' - there is invalid term 'null./src/stm32f0xx_hal_msp.c.d' in it.
Open '.cproject' file in project root - there is a reference to it as '*.c' resource in each build configuration(Debug/Release) section:

&lt;fileInfo id="ilg.gnuarmeclipse.managedbuild.cross.config.elf.release.1926846341.src/stm32f0xx_hal_msp.c" name="stm32f0xx_hal_msp.c" rcbsApplicability="disable" resourcePath="src/stm32f0xx_hal_msp.c.suxx" toolsToInvoke="ilg.gnuarmeclipse.managedbuild.cross.tool.c.compiler.1016695801.549052954"&gt;...&lt;/fileinfo&gt;

Workaround: if you remove the &lt;fileinfo&gt; XML entry manually out of '.cproject' file, 'subdir.mk' is generated correctly and build procedure goes on.

**Comment by edriouk** [comment]
@powerbroker, the problem you are describing, refers to another plugings that are not related to this repository.
Please address you issues here: https://github.com/gnuarmeclipse
