### ISSUE TITLE
CpPack.getInstallDir() does not account for pack name

### ISSUE THREAD

**Issue by mario-pi** [ARM-software/cmsis-pack-eclipse#12]
When constructing the installation path out of Pack properties, the method does not account for the pack name. Only vendor and version are used, so different packs from the same vendor will end up in the same folder. I am unsure though if this was by design, please correct me if this was intended behavior.

Patch with proposed change:
https://gist.github.com/mario-pi/4b41274ccf2ff149d2ed

**Comment by edriouk** [comment]
That is definitely a bug. Thank you for reporting it. Your patch will be included in the next release of the plug-in.

**Comment by edriouk** [comment]
fixed in release 1.1.0
