### ISSUE TITLE
Is pack generator supported by this plugin?

### ISSUE THREAD

**Issue by marek-trmac** [ARM-software/cmsis-pack-eclipse#18]
Hi,
I have a question (sorry if the issue is not right place where to ask): 
Is external generator supported by this plugin for configuration of the software? I mean this part of CMSIS specification: https://www.keil.com/pack/doc/CMSIS/Pack/html/pdsc_generators_pg.html

Are you aware of any example of such pack?

Thanks, Marek

**Comment by edriouk** [comment]
Generators support (processing of gpdsc files) is not implemented the plug-in yet, but planned. 
At the time being two applications have options to generate gpdsc packs: Infineon Dave and STM32CubeMX.

**Comment by marek-trmac** [comment]
Thanks for your answer. Do you have any estimation, when the feature will be supported?

**Comment by edriouk** [comment]
Currently I cannot provide any estimation, since target date has not been specified yet.

**Comment by edriouk** [comment]
Implemented in release 2.1.0
