### ISSUE TITLE
URL sometimes is not displayed complete

### ISSUE THREAD

**Issue by marek-trmac** [ARM-software/cmsis-pack-eclipse#19]
In NPW, URL sometimes is not displayed complete. I can reproduce it this way:
1. Click on the first derivative; Observation: layout updated and URL displayed
![first_click](https://cloud.githubusercontent.com/assets/16606103/14014780/f3f1d9a8-f1b4-11e5-9472-917201c2ae01.PNG)
2. Click on the last derivative (or any other derivative with longer name); Observation: URL not complete
![second_click](https://cloud.githubusercontent.com/assets/16606103/14014812/2adfac06-f1b5-11e5-8dc5-4e98b20f57f5.PNG)
3. Manually resize dialog; Observation: URL complete
![URL_complete](https://cloud.githubusercontent.com/assets/16606103/14014844/6c39ab2a-f1b5-11e5-9c16-c42685475a46.PNG)

**Comment by marek-trmac** [comment]
It would be good to detect, if layout needs to be updated

**Comment by edriouk** [comment]
Rejected: the proposed change interferes with layout engine and in case of a long URL completely hides the right side of the widget.
A tooltip to display the entire URL is  introduced in the 2.0 release instead.
