### ISSUE TITLE
no processors listed in RTE project wizard

### ISSUE THREAD

**Issue by hackrid** [ARM-software/cmsis-pack-eclipse#21]
Hi,

please see the screenshot below.

Notice that the stm32f4 pack is installed but it's not possible to select a processor from that dialogue.

eclipse MARS.2
CMSIS-Pack Eclipse Plug-in 1.1.0

![cmsis_packs](https://cloud.githubusercontent.com/assets/5111169/14846456/3038bb74-0c64-11e6-90b5-f73149e0899d.png)

**Comment by ilg-ul** [comment]
you probably need to configure again the path to the packages folder, these plug-ins do not automatically reuse the definition from the GNU ARM Eclipse Packs Manager.

**Comment by hackrid** [comment]
no success

**Comment by edriouk** [comment]
${cmisi_pack_root}, set by CMSIS Pack -> CMSIS Pack root folder preference

**Comment by hackrid** [comment]
ahh... did not noticed there were an extra preferences entry.

Window -> Preferences -> CMSIS Pack

now it lists the processor. thank you!
