### ISSUE TITLE
CMSIS-Core missing

### ISSUE THREAD

**Issue by hackrid** [ARM-software/cmsis-pack-eclipse#22]
I'm trying to create a RTE Config. But it's not straight forward.

can you tell me what I do wrong regarding the error shown in the picture below?
![cmsis_core](https://cloud.githubusercontent.com/assets/5111169/14851603/436e5290-0c81-11e6-971a-a3e306c6d124.png)

**Comment by jkrech** [comment]
The Pack Installer shows that it has CMSIS 4.5.0 installed, however the corresponding Cclass="CMSIS" is not visible in your Components window. Either you have installed the PACK while you were already configuring and the Model/Engine needs to reread the installed PACK descriptions, or the Folder where th pack installer installed the PACKs is different from where the Model reads the description from. Have you tried a refresh already ? (F5).

**Comment by edriouk** [comment]
F5 refreshes the project, not opened RTE editor. Either trigger cmsis_pack_root preference change or  close it and re-open the *.rteconfig file again.

**Comment by hackrid** [comment]
ahhh.... I did some reload tricks... close the project, switch workspace, switch back, reopen project.
it works now.

thank you very much!
