### ISSUE TITLE
Environment section string parsing code is broken

### ISSUE THREAD

**Issue by JohnKBartholomew** [ARM-software/cmsis-pack-eclipse#23]
In CpEnvironmentProvider.java/expandString() ine 202:
   char ch = output.charAt(i);
throws an exception when I'm stepping through it while it is parsing the contents of an <environment> section of my PDSC file. I think this code should be:
   char ch = input.charAt(i);

When I change a local copy of the plugin source to this and rebuild, it works as expected.

**Comment by edriouk** [comment]
Thank you for finding this, the fix has been pushed to the repository. The next binary release will contain it as well.

**Comment by JohnKBartholomew** [comment]
Verified the one-line fix identified above is now in the repository source. Thanks!
