### ISSUE TITLE
RteEvent has misspelled event names

### ISSUE THREAD

**Issue by jesperes** [ARM-software/cmsis-pack-eclipse#3]
In `RteEvent.java` the event string constants misspell "cmsis" as "comsis":

    public static final String CONFIGURATION_MODIFIED  = "com.arm.comsis.pack.rte.config.modified"; //$NON-NLS-1$

Not an actual problem, but my brain's spellchecker gets annoyed. :)

**Comment by edriouk** [comment]
Fixed in version 1.1.0
