### ISSUE TITLE
com.arm.cmsis.pack.build.ilg? (plug-in name suggestion)

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/cmsis-pack-eclipse#6]
Hi Evgueni,

I'm thrilled you named a plug-in after me, however I think more appropriate would be to refer to the project name (GNU ARM Eclipse).

What do you think about `com.arm.cmsis.pack.build.gnuarmeclipse`?

Regards,

Liviu

**Comment by edriouk** [comment]
Hi Liviu,

Agreed, I will rename the plug-in as you suggests in the next release. Thought it will impact already created projects since adapter id is written in .cproject file.   
Also I'll rename the adapter class accordingly.  

Regards,
Evgueni

**Comment by ilg-ul** [comment]
OK, thank you.

**Comment by edriouk** [comment]
renamed in release 1.1.0

**Comment by marek-trmac** [comment]
It seems this ticket could be closed, as it was already fixed
