### ISSUE TITLE
Do not automatically switch to C/C++ perspective after instantiating example projects

### ISSUE THREAD

**Issue by jesperes** [ARM-software/cmsis-pack-eclipse#60]
In our integration of the CMSIS plugins with IAR Embedded Workbench, I would like to be able to prevent the automatic switch to the C/C++ perspective. This happens unconditionally in `PackInstallerViewController`, but in our particular use case this is only confusing as the customer is expecting the example to appear in the IAR Embedded Workbench.

One solution to this would be to allow the `ICpEnvironmentProvider` have a default method for returning the perspective to switch to after copying example projects.

**Comment by edriouk** [comment]
I can publish a bug-fix release quite easy, in a couple of days. When do you need it?

**Comment by jesperes** [comment]
As soon as possible, but some time this week is perfectly ok.

**Comment by edriouk** [comment]
Please test the 2.3.2 release.

**Comment by ReinhardKeil** [comment]
Closing as no further feedback
