### ISSUE TITLE
Support needed for new CMSIS syntax element "<o key-identifier>*" 

### ISSUE THREAD

**Issue by RobertCrossman** [ARM-software/cmsis-pack-eclipse#68]
The CMSIS annotation has been expanded to include "\<o key-identifier\>* ".
Is there a plan to support this?

The annotation page: http://www.keil.com/pack/doc/CMSIS/Pack/html/configWizard.html#configWizard_annotations

**Comment by edriouk** [comment]
Yes, the support for that comes to the next release (not scheduled yet).

**Comment by RobertCrossman** [comment]
I have implemented support for the "<o identifier>" feature.  I've also forked the repository with the intent of contributing the code back thru a pull request.

Would you consider this?  If yes, do you have any requirements for contributed code?  I have commented my code, and will make several commits to my fork so I can explain/document my changes in smaller pieces.

**Comment by edriouk** [comment]
Hi Robert,
Contributions are welcomed via pull requests. 
We do not have official requirements for the code apar that it should be properly commented, avoids  vendor-specific features and additional dependencies as well as does not confilct with existing functionality .

Have you implemented the support for <-o key-identifier> feature? If yes, it could conflict with our implementation that is already done, but not yet published.

**Comment by edriouk** [comment]
Hi Robert,
The feature including your contribution is published in v2.4.0 release.
