### ISSUE TITLE
Installing pack requiring other pack without version always reinstall the required pack

### ISSUE THREAD

**Issue by TTornblom** [ARM-software/cmsis-pack-eclipse#72]
When installing a pack that has a <requirements> section requiring a <package ...> without a specified version, the installer attempts to install the latest version of the required pack even if it is already installed.

The required pack version appears to be inherited from the version of the pack being installed if it is not specified in the <package> tag.

Example:
A pdsc file containing the following sections:

```
  <releases>
      <release version="1.0.2" date="2018-04-19">
         - Updated pack to use latest version of CMSIS.
         - Updated Keil MDK and IAR example projects.
      </release>
...
   </releases>

   <requirements>
      <packages>
         <package name="CMSIS" vendor="ARM" />
         <package name="CMSIS-Driver" vendor="ARM" />
      </packages>
   </requirements>
```

will show a tool tip saying that it requires ARM.CMSIS.[1.0.2] and ARM.CMSIS-Driver.[1.0.2] even if the latest ARM.CMSIS and ARM.CMSIS-Driver packs are installed.

Adding a version= with a valid version number to the <package> tags stops it from reinstalling these packs.

The version= property is optional according to [http://www.keil.com/pack/doc/CMSIS/Pack/html/element_requirements_pg.html#element_packages](http://www.keil.com/pack/doc/CMSIS/Pack/html/element_requirements_pg.html#element_packages) and defaults to the latest available version, and this could likely be checked against the cached pdsc files to avoid reinstalling the packs if they are already at the latest available version.

**Comment by edriouk** [comment]
Fixed in v2.6.0
