### ISSUE TITLE
Assembly files .s not recognised, use of .S is mandatory

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/cmsis-pack-eclipse#8]
I tried to create a project for STM32F407, and I noticed that enabling Device/Startup brought a `startup_stm32f407xx.s` file to the project.

Please note that generally in Eclipse CDT managed projects (in GNU ARM Eclipse for sure), `.s` files are not included in the build, and assembly files need to be name with upper-case `.S`.

Regards,

Liviu

**Comment by edriouk** [comment]
I'm closing this issue here as it is not a plug-in problem, but packs.
