### ISSUE TITLE
Scroll bar on the device data books panel

### ISSUE THREAD

**Issue by sergio-soar-es** [ARM-software/cmsis-pack-eclipse#89]
Hi folks,

Thanks for the great work on the CMSIS-Pack plugin.
Is it possible to add a scroll bar in the device data books panel?
For our device (RSL10) we distribute a large number of documents and the documents list gets cropped, as shown in the image below.

Best regards,
Sergio.

![image](https://user-images.githubusercontent.com/7865215/67397564-59527400-f577-11e9-846d-3bf5b60c7c18.png)

**Comment by edriouk** [comment]
Hi Sergio,

yes, we'll include that fix in the next release 
Thank you for pointing to the problem.
Evgueni

**Comment by engsergiosoares** [comment]
Great, thanks, Evgueni!

**Comment by edriouk** [comment]
The toolbar appears  in version 2.10.0
