### ISSUE TITLE
Packs with requirements, without specifying version, requires incorrect version

### ISSUE THREAD

**Issue by TTornblom** [ARM-software/cmsis-pack-eclipse#91]
According to the CMSIS-Pack 1.6.0 specification the version number for a required pack is optional, but leaving it out causes the plugin to attempt to install the required pack in the same version as the pack being installed.

Example:
Maxim.MAX32650.pdsc contains the following pieces:
---
      <release version="1.1.0-a" date="2018-07-11">
         - Updates to ARM startup
      </release>
...
   <requirements>
      <packages>
         <package name="CMSIS" vendor="ARM"/>
      </packages>
...
   </requirements>
---

Installing this pack causes the plugin to attempt to install ARM.CMSIS.1.1.0-a, which seems wrong.

If a version number is available for the requirement then that version is used, which is the expected behavior.

**Comment by edriouk** [comment]
Fixed in v2.6.0
