### ISSUE TITLE
Compatibility 2020-06

### ISSUE THREAD

**Issue by oskrypnikov** [ARM-software/cmsis-pack-eclipse#93]
Could not install plugin on new version of Eclipse

**Comment by edriouk** [comment]
Could you please specify the Eclipse version and platform as well as the error message.

**Comment by oskrypnikov** [comment]
![зображення](https://user-images.githubusercontent.com/33432673/84989418-4e72d200-b14c-11ea-9c91-3216c1d0a7b2.png)
![зображення](https://user-images.githubusercontent.com/33432673/84989521-78c48f80-b14c-11ea-906c-6e174e12f5da.png)

**Comment by edriouk** [comment]
That is not the problem specific to CMSIS plug-ins, but rather Eclipse or Eclipse CDT.
I have tried to install another software from Eclipse update site, the result is the same:
![Eclipse2020_06InstallProblem](https://user-images.githubusercontent.com/10760440/84998192-ce4e6b80-b14f-11ea-8963-7e43f946f2f6.png)

**Comment by edriouk** [comment]
Update: the problem is in Eclipse for C/C++ 2020.06
The plug-ins are successfully installed in Eclipse for RCP and RAP

**Comment by edriouk** [comment]
Here is the comment CDT team: 
The workaround is to do the installation while running Eclipse with Java >= 11. You can then revert back to using Java 8 once you are done installing.

**Comment by edriouk** [comment]
The next version of CMSIS plug-ins will require JavaSE-11 as a minimum.

**Comment by oskrypnikov** [comment]
Thank you very much. Installed JSE 14.0.1 and switched eclipse to this version by eclipse.ini file. Everything is OK.
added

-vm
C:/Program Files/Java/jdk-14.0.1/bin/javaw.exe

before "-vmargs"
