### ISSUE TITLE
CMSIS pack software Components/Libraries source files should be read-only

### ISSUE THREAD

**Issue by avi-77** [ARM-software/cmsis-pack-eclipse#98]
Hello,

In Keil, on copying the samples using the CMSIS pack manager, the components source/header files are read-only (i.e. user cannot modify the component/libraries files) as shown below:
![image](https://user-images.githubusercontent.com/79654418/134410237-9e9eaf9e-0074-4b73-92ab-9c91d0997e06.png)

![image](https://user-images.githubusercontent.com/79654418/134411091-0252d833-913b-4a85-a920-ebab86db51e6.png)

But in Eclipse components source/header files can be modified, which shouldn't be the case. 

Is it possible to add the read-only functionality to software components in CMSIS pack for Eclipse?

**Comment by edriouk** [comment]
The files are read-only,  but Eclipse Project Explorer does not indicate that. Attempting to edit a file brings a message box asking to make file writable .
