### ISSUE TITLE
Schema version "1.7.2" not recognised, package Keil.STM32F0xx_DFP.pdsc ignored.

### ISSUE THREAD

**Issue by atilkowski** [ARM-software/cmsis-pack-eclipse#99]
Hi.
I have installed a 2.6.1 release of a plugin.
After running "refresh" the pdsc files are cached but afterwards many of them are ignored and not installed.
At least that is what happens with most of STM32 CMSIS files, it appears most Keil's pdsc files of STM32 were updated recently to new schema.

Schema version "1.7.2" not recognised, package Keil.STM32F0xx_DFP.pdsc ignored.
--
Alex

**Comment by edriouk** [comment]
Hi, could you please provide more information, at least a screenshot of the error.
The plug-ins do not check schema by default processing for performance reasons. 
Therefore I wonder where this message come from

**Comment by atilkowski** [comment]
No problem.
I attach a screenshot made after refresh and also txt of all "..ignored" messages.
If that could help, I use Windows 7, 32-bit, Eclipse release 2018-09, Java 1.8.0_281.

Interestingly, this whole thing worked for the last year (Keil.STM32F0xx_DFP.2.1.0.pdsc, uses schema version 1.6.0) till I decided to refresh yesterday. New Keil.STM32F0xx_DFP.2.1.1.pdsc file uses schema version 1.7.2.

Because of this incompatibility, whole processor family was removed so now I cannot even revert to old, working 2.1.0 version. 
If you need some further info - let me know.

![After refresh](https://user-images.githubusercontent.com/102521592/160413661-a5deb163-114d-4264-9e40-9dfc8ab4fcf2.jpg)


[Ignored.txt](https://github.com/ARM-software/cmsis-pack-eclipse/files/8363391/Ignored.txt)

**Comment by edriouk** [comment]
Hi,
that is not CMSIS-Eclipse plug-ins. 
Your screenshot shows "Embedded C/C++ CMSIS Pack (Experimental)" feature. That is absolutely independent developments that is completely separate from CMSIS Eclipse Plug-ins. 
Our CMSIS- Pack Manager perspective should look like as follows: 
![image](https://user-images.githubusercontent.com/10760440/160423065-7b54b1dd-9230-4d5d-b414-6be5c380e3b3.png)

**Comment by atilkowski** [comment]
Thanks, that explains everything.

**Comment by edriouk** [comment]
FYI, as far as I know the "Embedded C/C++ CMSIS Pack (Experimental)" feature is maintained by  https://mcuoneclipse.com

**Comment by ilg-ul** [comment]
The plug-in is part of [Eclipse Embedded CDT](https://projects.eclipse.org/projects/iot.embed-cdt).

Support for 1.7.x was added some time ago, please update your Eclipse.
